function plotMeans(M, sym, color, edgeColor)
white = [1 1 1];
markerSize = 10;
plot(M(1, :), M(2, :), sym, 'MarkerEdgeColor', white, ...
    'MarkerFaceColor', white, ...
    'MarkerSize', markerSize + 5);
plot(M(1, :), M(2, :), sym, ...
    'MarkerEdgeColor', edgeColor, ...
    'MarkerFaceColor', color, ...
    'MarkerSize', markerSize);
